GET http://localhost:5000/api/v1/user/sdadad
###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
  "numberPhone": "0769394553",
  "password": "Phatdat123456"
}
###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "numberPhone": "0769394553",
  "password": "Phatdat123456"
}
###
GET http://localhost:5000/api/v1/category/getCategory
###
PUT http://localhost:5000/api/v1/category/updateCategory/7
Content-Type: application/json

{
  "name": "Thể hình",
  "description": "Bao gồm các dịch vụ như tìm phòng gym, yoga, pilates"
}
###
POST http://localhost:5000/api/v1/category/createCategory
Content-Type: application/json

{
  "name": "Thể hình",
  "description": "Dịch vụ về thể chất"
}
###
DELETE http://localhost:5000/api/v1/category/deleteCategory/6
###
GET http://localhost:5000/api/v1/service/getService

###
POST http://localhost:5000/api/v1/service/createService
Content-Type: application/json

{
  "name": "Massage Thư giản",
  "description": "Thực hiển bởi chuyên viên massage có kinh nghiệm và kĩ năng cao",
  "duration_minutes": 60,
  "price": 120000,
  "category_id": 1
}
###
PUT http://localhost:5000/api/v1/service/updateService/3
Content-Type: application/json

{
  "name": "Massage Thư giản",
  "description": "Thực hiển bởi chuyên viên massage có kinh nghiệm và kĩ năng cao",
  "duration_minutes": 60,
  "price": 120000,
  "category_id": 3
}
###
DELETE http://localhost:5000/api/v1/service/deleteService/3